# Generated by Django 4.1.7 on 2023-04-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_truncatetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='truncatetable',
        ),
        migrations.RemoveField(
            model_name='values',
            name='membership',
        ),
        migrations.AddField(
            model_name='values',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='values',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='values',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='values',
            name='dob',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='values',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='values',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='values',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='values',
            name='member',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AddField(
            model_name='values',
            name='organisation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='values',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='values',
            name='qualification',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='values',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='values',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='values',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='values',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
