# Generated by Django 4.0.6 on 2023-06-19 14:36

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardspage',
            name='year',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='awardspage',
            name='body',
            field=wagtail.fields.RichTextField(verbose_name='body'),
        ),
    ]
