# Generated by Django 4.0.6 on 2023-06-19 14:59

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_awardspage_year_alter_awardspage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencepage',
            name='year',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='conferencepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='body'),
        ),
    ]
