# Generated by Django 4.0.6 on 2023-06-19 15:00

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_conferencepage_year_alter_conferencepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencepage',
            name='year',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='year'),
        ),
    ]
