# Generated by Django 4.0.6 on 2023-06-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_conferencepage_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshoppage',
            old_name='body',
            new_name='year',
        ),
    ]
