# Generated by Django 4.0.6 on 2023-06-19 17:05

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_newsletterindexpage_newsletterpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterpage',
            name='date',
        ),
        migrations.AddField(
            model_name='newsletterpage',
            name='issue',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsletterpage',
            name='month',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsletterpage',
            name='volume',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsletterpage',
            name='year',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
